services:
  db:
    container_name: webDinamica-database
    image: mariadb
    ports:
      - 3309:3306
    restart: always
    volumes:
      - C:/bbdd/WebDinamica_db:/var/lib/mysql
      - ./www_sql_estructura.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MARIADB_ROOT_PASSWORD: abcd1234@
      MARIADB_USER: webdinamica
      MARIADB_PASSWORD: abcd1234@
      MARIADB_DATABASE: app_abel
    networks:
      net: 
        ipv4_address: 172.30.1.2

  www:
    build:
      context: .
    container_name: webDinamica-www
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    ports:
      - 85:80

    networks:
      net:
        ipv4_address: 172.30.1.3

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
