services:
  www:
    build:
      context: .
    container_name: webEstatica-www
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    ports:
      - 80:80

    networks:
      net:
        ipv4_address: 172.30.1.3

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
