version: '3.8'
services:
 app:
    container_name: letschat
    image: sdelements/lets-chat
    restart: always
    environment:
      LCB_DATABASE_URI: mongodb://mongo/letschat
    ports:
      - 80:8080
    depends_on:
      - db
 db:
   container_name: mongo
   image: mongo:3.4
   restart: always
   volumes:
     - C:/bbdd/letschat:/data/db